### ISSUE TITLE
Canceling a running query kills extension

### ISSUE THREAD

**Issue by bporterfield** [malloydata/malloy-vscode-extension#131]
Pressing cancel when running a query consistently kills extension for me, resulting in all future queries erroring like: 

<img width="358" alt="Screenshot 2023-05-06 at 6 05 21 PM" src="https://user-images.githubusercontent.com/108260/236652583-a39f98f3-60be-41f4-a369-9aa3468e9067.png">

Reproduce using a longer-ish running query - press Run Query then press Cancel in progress bar in lower right. [This query](https://github.com/malloydata/malloy-samples/blob/main/bigquery/faa/flights.malloy#L57) lets me do it consistently. Exception is:

```
Exception has occurred: Error: Request malloy/queryPanel failed with message: Webview is disposed
  at handleResponse (/Users/bporterfield/dev/malloydata/malloy-vscode-extension/dist/server_node.js:2100:40)
    at processMessageQueue (/Users/bporterfield/dev/malloydata/malloy-vscode-extension/dist/server_node.js:1938:13)
    at Immediate._onImmediate (/Users/bporterfield/dev/malloydata/malloy-vscode-extension/dist/server_node.js:1924:11)
    at process.processImmediate (node:internal/timers:466:21)
    at process.callbackTrampoline (node:internal/async_hooks:130:17)
```

Appears to be related to recent change to combine worker and server, trying a build from before that merge did not reproduce the error.

**Comment by caleb-c-li** [comment]
The original implementation is when a 'Cancel' button was hit, the webview is disposed immediately. The appears to be an issue when the legacy worker functionalities were moved to the LSP server side, such that a 'Cancel' and a subsequent web view dispose() can cause the LSP server thinks the LSP client is unhealthy therefore LSP server is restarted. The errors observed as follows:

```
ResponseError: Request malloy/queryPanel failed with message: Webview is disposed
    at handleResponse (/Users/calebli/work/malloy-vscode-extension/dist/server_node.js:2100:40)
    at processMessageQueue (/Users/calebli/work/malloy-vscode-extension/dist/server_node.js:1938:13)
    at Immediate.<anonymous> (/Users/calebli/work/malloy-vscode-extension/dist/server_node.js:1924:11)
    at process.processImmediate (node:internal/timers:466:21) {
  code: -32603,
  data: undefined
}
[Info  - 10:17:13 AM] Connection to server got closed. Server will restart.
Debugger listening on ws://127.0.0.1:6009/b8a59cfb-a3fa-4c4f-9907-0c9675ce7ef5
For help, see: https://nodejs.org/en/docs/inspector
NodeMessageHandler initialized.
[Info  - 10:17:13 AM] Server loaded
[Info  - 10:17:13 AM] Server onInitialize
```

The orphan client is no longer valid, thus, "unhandled method malloy/fetch" is observed.

It might be less of an issue when the legacy workers can hide some of cancellation from LSP client to LSP server. When the worker functionalities were moved to LSP server. We probably want to handle cancellation with better state control.

A fix I have in mind is to introduce a `Cancelled` state such that the LSP server responded with the `Cancelled` state so that the LSP client can invoke web view dispose() when LSP server is done with its work.
